### ISSUE TITLE
Parsing error allocating a new virtual machine template

### ISSUE THREAD

**Issue by sneumann** [mangelft/terraform-rke-paas#1]
Hi, 
I am getting a parsing error applying the plan:
```
* opennebula_vm.k8s-node[0]: 1 error(s) occurred:
* opennebula_vm.k8s-node.0: [one.template.instantiate] Error allocating a new virtual machine template. 
Error parsing: 
DISK_ID=1@^_^@NETWORK=YES@^_^@SET_HOSTNAME=$$NAME@^_^@SSH_PUBLIC_KEY=$$USER[SSH_PUBLIC_KEY]@^_^@TARGET=hda@^_^@USERNAME=$$UNAME. 
syntax error, unexpected EOA, expecting $end or VARIABLE or RSTRING at line 0, columns 45:46
```

I have used terraform before, but not sure how to debug the above. 
Yours, Steffen

TF stuff installed today using 
```
Terraform v0.11.10
+ provider.local v1.1.0
+ provider.opennebula (unversioned)
+ provider.rke (unversioned)
+ provider.template v2.0.0
```

Our OpenNebula is `OpenNebula 5.6.1` and indeed there is a forum entry:
`Problem updating Contextualisation Custom Vars Key Value containing a $`
https://forum.opennebula.org/t/problem-updating-contextualisation-custom-vars-key-value-containing-a/6072/7

**Comment by sneumann** [comment]
Editing `k8s-template.tpl` and replacing `$$` with `§§` gets me successfully a template, 
```
$ onetemplate show 43
TEMPLATE 43 INFORMATION                                                         
ID             : 43                  
NAME           : k8s-template        
REGISTER TIME  : 02/11 20:33:29      
...
TEMPLATE CONTENTS                                                               
CONTEXT=[
  NETWORK="YES",
  SET_HOSTNAME="§§NAME",
  SSH_PUBLIC_KEY="§§USER[SSH_PUBLIC_KEY]",
  USERNAME="§§UNAME" ]
CPU="2"
...
```
which will - of course - not work downstream creating the actual nodes. 
Ideas ? Maybe @CSUC ? Yours, Steffen

**Comment by mangelft** [comment]
Hi Steffen,

Me to apologize for the delay of our response. The new way to install HA Rancher is using **helm chart**.

https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/

therefore this code is DEPRECATED.

About the parsing error, I recommend using the **parameter context** in the opennebula_vm resource and not create a new template.

You can get a complete example at the following URL:
https://github.com/iguanesolutions/terraform-provider-opennebula/wiki/Virtual-Machines


Kind Regards,

M. Ángel
